WebApplication3/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3.Context;

namespace WebApplication3.Models
{
    public class Article
    {
        public int id { get; set; }
        public String tittle { get; set; }

        public DateTime date
        {
            get;
            set;
        }

        public TimeSpan time { get; set; }
        public String info { get; set; }


        public String getFull()
        {
            return new NewsContext().pages.First(x=>x.id==id).Full;
        }

        public string getDate()
        {
            return date.ToString("dd MMMM yyyy");
        }
        public static List<Article> getTempArts(int count)
        {
            var list = new List<Article>();
            for (var i = 0; i < count; i++)
                list.Add(new Article
                {
                    id = i,
                    date = DateTime.MinValue,
                    info = "info info info info info info info info",
                    tittle = "tittle tittle",
                    time = TimeSpan.MinValue
                });
            return list;
        }

        public static Article getLast()
        {
            try
            {
                var db = new NewsContext();
                return db.article.OrderByDescending(x => x.date).ThenByDescending(x => x.time).First();
            }
            catch (Exception)
            {
                return getTempArts(1)[0];
            }
        }

        public static Article getById(int id)
        {
            try
            {
                var db = new NewsContext();
                return db.article.First(x => x.id == id);
            }
            catch (Exception)
            {
                return null;
            }
        }

        public static List<Article> getArts(int page)
        {
            try
            {
                NewsContext db = new NewsContext();
                int skip = 6 * (page - 1);
                return db.article.OrderByDescending(x => x.date).ThenByDescending(x => x.time).Skip(skip).Take(6).ToList();
            }
            catch (Exception e)
            {
                return getTempArts(6);
            }
        }

        public object getName()
        {
            throw new NotImplementedException();
        }
    }
}

WebApplication3/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Context;
using WebApplication3.Models;
using System.IO;

namespace WebApplication3.Controllers
{
    public class ArticlesController : Controller
    {
       
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create([Bind("id,tittle,date,time,info,full,file")] ArticleModel art)
        {
            if (ModelState.IsValid && art.file != null)
            {
                byte[] file = null;
                using (var binaryReader = new BinaryReader(art.file.OpenReadStream()))
                {
                    file = binaryReader.ReadBytes((int)art.file.Length);
                }
                using (NewsContext _context = new NewsContext())
                {
                    Article article = new Article() { id=art.id, date = art.date, tittle = art.tittle, info = art.info.Substring(0, 195) + "...", time = art.time};
                    ArticleImages image = new ArticleImages() { id=art.id, name=art.file.FileName, img = file};
                    Pages page = new Pages() { id=art.id, Full=art.full};
                    


                    _context.article.Add(article);
                    _context.articleimages.Add(image);
                    _context.pages.Add(page);

                    _context.SaveChanges();
                    return Content("ok");
                }
            }
            return View(art);
        }

        public IActionResult Delete(int id)
        {
            using (NewsContext _context = new NewsContext())
            {
                const string query = "DELETE FROM mydb.article WHERE id = {0}";
                const string query2 = "DELETE FROM mydb.pages WHERE id = {0}";
                const string query3 = "DELETE FROM mydb.articleimages WHERE id = {0}";
                _context.Database.ExecuteSqlCommand(query, id);
                _context.Database.ExecuteSqlCommand(query2, id);
                _context.Database.ExecuteSqlCommand(query3, id);
            }
                return Content("ok");
        }
    }

}

WebApplication3/Views/Articles/Create.cshtml
@model WebApplication3.Models.ArticleModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

 <form asp-action="Create" asp-controller="Articles" method="post" enctype="multipart/form-data">
        <div class="form-horizontal">
            <h4>ArticleModel</h4>
            <hr />
            <div class="form-group">
                <label asp-for="id" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="id" class="form-control" />
                    <span asp-validation-for="id" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="tittle" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    @Html.TextArea("tittle", string.Empty, 5, 120, null)
                    <span asp-validation-for="tittle" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="date" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="date" class="form-control" />
                    <span asp-validation-for="date" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="time" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="time" class="form-control" />
                    <span asp-validation-for="time" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="info" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    @Html.TextArea("info", string.Empty, 10, 120, null)
                    <span asp-validation-for="info" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="full" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    @Html.TextArea("full", string.Empty, 70, 120, null)
                    <span asp-validation-for="full" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="file" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input name="file" type="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>